// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCj7OcisqNMnDZH_URxnZE4i-Xmt5ghxxk',
    appId: '1:619147283505:web:afa1e9ef277438fce7d910',
    messagingSenderId: '619147283505',
    projectId: 'friday-65f8f',
    authDomain: 'friday-65f8f.firebaseapp.com',
    storageBucket: 'friday-65f8f.appspot.com',
    measurementId: 'G-R40PPMDVL4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_fkqP5wMPDtB2WdFfD-esHD485L2nhBU',
    appId: '1:619147283505:android:fa45f5f55542739fe7d910',
    messagingSenderId: '619147283505',
    projectId: 'friday-65f8f',
    storageBucket: 'friday-65f8f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOwp2XMS9AZVZ6uTT2t13-A4ymhHUmBlU',
    appId: '1:619147283505:ios:e255277abb21023ee7d910',
    messagingSenderId: '619147283505',
    projectId: 'friday-65f8f',
    storageBucket: 'friday-65f8f.appspot.com',
    iosBundleId: 'com.example.fire',
  );
}
